services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./DbInit:/docker-entrypoint-initdb.d
    networks:
      - internal-network
      - external-network

  pgAdmin:
    image: elestio/pgadmin:REL-9_8
    restart: always
    container_name: pgAdmin
    ports:
      - "8080:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    networks:
      - external-network
      - internal-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin 
    depends_on:
      - postgres-db

volumes:
  db-data:
  pgadmin-data:

networks:
  internal-network:
    driver: bridge
    internal: true
  external-network:
    driver: bridge
    